import { ABLATION, CLOUD, ILLUSTRATIVE, METRICS, PROTOCOL } from './metrics.gen'

export { ABLATION, CLOUD, ILLUSTRATIVE, METRICS, PROTOCOL }

export const COMPARISON = [
  { label: 'Lined-up clouds', pct: METRICS.otPct, tone: 'good' as const },
  { label: 'No transport', pct: METRICS.noOtPct, tone: 'bad' as const },
  { label: 'Majority class', pct: METRICS.majorityPct, tone: 'muted' as const },
  { label: 'Chance', pct: METRICS.chancePct, tone: 'muted' as const },
]

export const DECISIONS = [
  {
    first: 'Shuffle source and target together, then report accuracy',
    built: 'Train on source, score only on target, and print OT next to no-OT',
  },
  {
    first: 'Retrain a large net on the target',
    built: 'Keep a small logistic head; move the source points with Sinkhorn',
  },
  {
    first: 'Use cosine distance because it is common in embeddings',
    built: 'Default to squared Euclidean; cosine is an ablation that can fail',
  },
  {
    first: 'Pull MNIST and USPS for the first run',
    built: 'Use a capped 2D Gaussian shift so the number is measured without a download',
  },
] as const

export type Tool = { name: string; tag: string; plain: string; tech: string }
export const STACK: Tool[] = [
  {
    name: 'numpy Gaussians',
    tag: 'data',
    plain: 'Builds two labeled clouds. Same three classes, target shifted in the plane.',
    tech: `Source n=${PROTOCOL.nSource}, target n=${PROTOCOL.nTarget}, ${PROTOCOL.nClasses} classes. Sample cap ${PROTOCOL.nSource} per side, well under the 5k DESIGN cap.`,
  },
  {
    name: 'POT Sinkhorn',
    tag: 'transport',
    plain: 'Moves source points onto the target cloud without using target labels.',
    tech: `Squared Euclidean cost, ε=${PROTOCOL.eps}. Barycentric map, then a classifier on the mapped source.`,
  },
  {
    name: 'scikit-learn logistic',
    tag: 'head',
    plain: 'The classifier that has to work on the target after the move.',
    tech: 'Logistic regression fit on mapped source features. The no-OT baseline is the same head fit on raw source, scored on the same target.',
  },
  {
    name: 'pytest leak checks',
    tag: 'split',
    plain: 'Fails the run if source ids or labels sneak into the target score.',
    tech: 'Headline split is source-train / target-test. Mixing domains and shuffling is caught as a leak, not reported as the result.',
  },
  {
    name: 'Vite + React',
    tag: 'page',
    plain: 'This walkthrough. The charts read numbers from data.ts. No API.',
    tech: 'Static TypeScript module generated by scripts/run.py. Tailwind on Vite. Charts are SVG in the same shell as the other walkthroughs.',
  },
]

export const NEXT = [
  'Swap the Gaussians for MNIST source and USPS target once the files are local, same split and metric.',
  'Try a frozen small CNN embedding instead of the raw 2D features, still scoring only on target.',
  'Add one more cost (Mahalanobis) only if squared Euclidean stops working on the digit pair.',
]

export const SECTORS = [
  {
    name: 'Medical imaging',
    note: 'A detector trained at one scanner, read on another hospital’s machine.',
  },
  {
    name: 'Speech',
    note: 'A keyword model trained on headset audio, scored on far-field room mics.',
  },
  {
    name: 'Remote sensing',
    note: 'Labels from ground plots, features from a satellite pass with a different calibration.',
  },
]
